name: ServerSelectorGUI
version: '1.20-R0.1-SNAPSHOT'
main: serverselectorplugin.serverselectorgui.ServerSelectorGUI
api-version: '1.20'
commands:
  servers:
    description: "opense the servers GUI"
    usage: "/servers"
